### ISSUE TITLE
Define Splash screen for Labtab and app icon

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#1]
Need to design loading splash screen and app icon for Android. For the splash screen I was thinking maybe the one from Wizbench itself? The icon I'm not sure to be honest, I'll leave it up to Tatyana.

**Comment by solnishka** [comment]
I suggest to use this part of logo as an icon for our application:
![icon-for-the-application](https://cloud.githubusercontent.com/assets/9883696/19965464/298e6008-a1d8-11e6-8f64-4d7b914a6e9c.png)

**Comment by internetmosquito** [comment]
Ok, looks good to me, transparent background right?

**Comment by internetmosquito** [comment]
What about splash screen?

**Comment by solnishka** [comment]
There are 3 variants of splash - the one is that we already have for Wizbench, and 2 new:

![splash-1](https://cloud.githubusercontent.com/assets/9883696/19978022/8f9c4db4-a206-11e6-862a-2b68da982c0c.jpg)

![splash-2](https://cloud.githubusercontent.com/assets/9883696/19978027/965d7858-a206-11e6-9bdb-9c79e6da5f1f.jpg)

![splash-3](https://cloud.githubusercontent.com/assets/9883696/19978034/9c6f762e-a206-11e6-8e4c-e58e6290c06e.jpg)

@internetmosquito, what do you think?

**Comment by solnishka** [comment]
> Ok, looks good to me, transparent background right?

sure

**Comment by internetmosquito** [comment]
Love the second one! Super job!

**Comment by solnishka** [comment]
@kapoorutd, the final version of splash screen you can take here: 
![splash-2](https://cloud.githubusercontent.com/assets/9883696/20000415/5dc0b5d2-a288-11e6-88ec-a6cbb82178b5.png)

**Comment by internetmosquito** [comment]
@kapoorutd can we use this as a splash screen? What about the app icon?

**Comment by internetmosquito** [comment]
@kapoorutd Splash screen does not stretch to screen size, please fix it
