### ISSUE TITLE
Fix several issues in build 1.8.3

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#101]
It looks like latest build has several issues.

* There is a problem with selecting members when making a video, the height of the dropddown does not adjust to the number of selected members or available ones, check image below

![errorlist](https://user-images.githubusercontent.com/1500392/49793706-1a884680-fd36-11e8-9ed2-b9016e683674.png)

Please use a modal dialog for selecting members instead of drop-down...just as we do with nuggets, but without grouping, just a list of selectable members 

* It seems the font size has changed from previous build 1.8.2 and also,

![ne](https://user-images.githubusercontent.com/1500392/49799635-b79eab80-fd45-11e8-8c17-e649d2aa9c01.png)

* Looks like selected members are not arranged correctly

![errorn](https://user-images.githubusercontent.com/1500392/49793791-45729a80-fd36-11e8-8373-f20badf4b9d4.png)

**Comment by kapoorutd** [comment]
@internetmosquito we didn't changed anything regarding font size after v1.8.2, please try to install v1.8.2 on the same device and compare the font size with that version.

**Comment by internetmosquito** [comment]
@kapoorutd what about the first issue? not the font size one

**Comment by kapoorutd** [comment]
We implement dialog for first one

**Comment by internetmosquito** [comment]
@kapoorutd what is that supposed to mean?

**Comment by kapoorutd** [comment]
@internetmosquito Please use a modal dialog for selecting members instead of drop-down...just as we do with nuggets, but without grouping, just a list of selectable members > We Implemented a dialog for selecting members.

![screenshot 2018-12-17 at 4 13 37 pm](https://user-images.githubusercontent.com/6163203/50345805-543b2780-0556-11e9-8c84-41af602d834f.png)

**Comment by internetmosquito** [comment]
@kapoorutd  understood but then....how Dmitry managed to select them in his screenshot??

**Comment by kapoorutd** [comment]
Didn't understand

**Comment by internetmosquito** [comment]
@kapoorutd  I'm asking how could Dmitry (our QA guy) come to the screen he captured (first one posted in this issue)...

**Comment by kapoorutd** [comment]
Screenshot was taken with v1.8.3, you have to create new build v1.8.4 to see this dialog

**Comment by internetmosquito** [comment]
oh, ok, let me try it out

**Comment by internetmosquito** [comment]
@kapoorutd Regarding the modal to select students, can you add a close button, or Cancel? right now the only chance is to actually click Save or Back button which is not the best UX

**Comment by kapoorutd** [comment]
@internetmosquito put cancel button on Dialog 
![screenshot 2018-12-24 at 5 44 21 pm](https://user-images.githubusercontent.com/6163203/50399179-973e0a80-07a3-11e9-8d87-03d28cf9afc0.png)

**Comment by internetmosquito** [comment]
@kapoorutd Ok, but please don't close tickets, only I should be able to close tickets after QA confirms are good to make a release, thanks!
