### ISSUE TITLE
Not able to login sometimes with v1.8.3 

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#102]
It seems sometimes is not possible to login even if the tablet is connected to Internet.

We tested with previous version 1.8.1 versus 1.8.3 and while this did not happened in 1.8.1 it happened several times with 1.8.3

Appending logs for each version

[labtab_1.8.1_logs.zip](https://github.com/wizbots/labtab/files/2667465/labtab_1.8.1_logs.zip)
[labtab_1.8.3_logs.zip](https://github.com/wizbots/labtab/files/2667466/labtab_1.8.3_logs.zip)

**Comment by internetmosquito** [comment]
Ok, will check

**Comment by internetmosquito** [comment]
@kapoorutd this seems to still be happening, please check the attached logs, Dima used user chanel@wizbots.com / Getmoney1

[logs (1).zip](https://github.com/wizbots/labtab/files/2706330/logs.1.zip)

**Comment by kapoorutd** [comment]
@internetmosquito we increased socket time for connection and also done some changes on log, please try now and share logs if still facing problem with login

**Comment by internetmosquito** [comment]
This was released on 1.8.6
