### ISSUE TITLE
Duplicated member when creating project video

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#112]
There is a strange situation when the user selected appears duplicated

How to reproduce:

- login to the labtab app;
- click LabList;
- select a program;
- click absences - if there's none, mark absent a student in the previous screen;
- select member;
- click add video;
- click cancel;
- select member again;
- click add video;
- click cancel;
- The selected member appears twice in the Project creators field

![dupl](https://user-images.githubusercontent.com/1500392/52042732-32ae6200-253e-11e9-8aad-abcab2f224ac.png)

Attached logs 
[dupl.zip](https://github.com/wizbots/labtab/files/2816367/dupl.zip)

**Comment by internetmosquito** [comment]
@kapoorutd This is still happening

Found in: v1.8.9

How to reproduce:

- login to the labtab app;
- click LabList;
- select a program;
- click absences - if there's none, mark absent a student in the previous screen;
- select member;
- click add video;
- click LabList;
- click back button at the tab;
Actual:
   The selected member appears twice in the Project creators field

**Comment by kapoorutd** [comment]
@internetmosquito 
We have fixed it and verified at our end and pushed the code in m_zero branch .
Please take a pull from same branch and verify the changes.
