### ISSUE TITLE
MadLib is not present when editing existing project

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#117]
When editing a project there is no MadLib in the dropdown in version 1.8.7, please include it

**Comment by kapoorutd** [comment]
@internetmosquito 

I have checked the above mentioned issue by taking the pull from "m_zero" branch and feature you were asking exist in this branch. 
To fix the mentioned issue, I need v1.8.7 build code. Please do the needful.

**Comment by kapoorutd** [comment]
@internetmosquito 
I have checked the above mentioned issue by taking the pull from "m_zero" branch and Now Its showing MadLib when editing the existing project.

**Comment by internetmosquito** [comment]
Dima, please test this

**Comment by internetmosquito** [comment]
Tested and released
