### ISSUE TITLE
Improve adding video  process

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#121]
Right now when we select a student(s) and we start creating a video, it happens very often that, since we have to click the back button to hide the keyboard when adding the required data, we hit the back button more than once and we completely go out of adding video window.

This has a SEVERE consequence, which is, we have to re-create the video, because there's no way to select an existing video when making a video. This needs to change.

Right now when we create a new video we see this:

![Screenshot_20190310-195605_LabTab](https://user-images.githubusercontent.com/1500392/54090020-ccec9b80-436f-11e9-8451-1ac1d2dbeb0b.jpg)

So let's do a couple things to improve this situation:

1.- When making a new video and clicking in the "No preview available" frame, instead of showing the camera right away, show a modal asking if they want to select an existing video or make a new video.

a.- If select an existing video is tapped, then show video gallery and let user select an existing video.
b.- If Make a new video is tapped, proceed as we do now, just open the camera to start recording.

2.- If user accidentally clicks back in this view, show a modal asking if they really want to leave the video creation. This way we can avoid this scenario as much as possible.

**Comment by kapoorutd** [comment]
Sure will be done .

**Comment by kapoorutd** [comment]
@internetmosquito 
I have fixed the above issue and checked at my end and pushed the code in m_zero branch .
Please have a look into it and confirm.
