### ISSUE TITLE
App crashing when trying to make a video

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#122]
In version 1.8.8 the app is crashing every time we try to make a video

The labtab is closed when trying to add the video:
reproduce in staging:
- login to the labtab with chanel@wizbots.com;
- select lablist;
- select a program to add video;
- at the add video section click to record the video;
Actual:
  The notification appears, which stops the app.

Logs attached
[logs.zip](https://github.com/wizbots/labtab/files/2960828/logs.zip)

**Comment by kapoorutd** [comment]
@internetmosquito 
I have checked the above mentioned issue by taking the pull from "m_zero" branch and the bug you have shared is not in m_zero branch which is on github v1.8.7
To fix the mentioned issue, I need v1.8.8 build code. Please do the needful.

**Comment by internetmosquito** [comment]
@kapoorutd  not sure what you mean, m_zero and master are identical...I created v1.8.8 from m_zero, merged into master and made tag v1.8.8

**Comment by kapoorutd** [comment]
@internetmosquito 
This is to inform you that the targetSdkVersion has changed from 23 to 25 and for 25 (i.e nougat) We need some extra permission for accessing URI i.e We need add file provider for api level 25 that is not present in the current code base.
So, Please whenever there is any change made for targetSdkVersion in future, let us know.
Now I am fixing it and update you.

**Comment by kapoorutd** [comment]
@internetmosquito 
We've fixed the above issue and cross check the previous issues.
We have pushed the fixes in m_zero branch , Please take a pull from same branch and verify the changes.

**Comment by internetmosquito** [comment]
thanks, will check! @kapoorutd
