### ISSUE TITLE
Wrong version number in settings

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#125]
Found in: v1.8.9

How to reproduce:

    login to the labtab (staging) with chanel@wizbots.com;
   go to settings

Actual:
Shown version is not latest one 1.8.9

**Comment by kapoorutd** [comment]
@internetmosquito 
This is to inform you that whenever you changed Version name you also need to change same in the source code (in gradle file), We have checked the v1.8.9 source code its has same v1.8.7 that is why it does not reflecting in setting.
Now I am fixing it and will update  you.

**Comment by kapoorutd** [comment]
@internetmosquito 
We've fixed the above issue and verified at our end and pushed the code in m_zero branch .
Please take a pull from same branch and verify the changes.
