### ISSUE TITLE
Create new button to show roster for a lab

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#127]
We need a new button next to show details that will show a PDF with roster data for the selected lab. Check image below

![20190430_223621_rmedited](https://user-images.githubusercontent.com/1500392/57201017-4c26d600-6f93-11e9-9b71-f8a8f30c2bf5.jpg)

The roster should be very close to the one attached 
[42837.pdf](https://github.com/wizbots/labtab/files/3146095/42837.pdf)

Eventually we might show this on the labtab itself instead of PDF but for now is ok.

New endpoint /roster in API will be made available shortly

**Comment by alexey-ku77** [comment]
@kapoorutd please specify in which way will be more convinient for you to retrieve the pdf?
Via json body with pdf data specified base64 encoded or pdf data in http body?

**Comment by kapoorutd** [comment]
@alexey: I am out of station for this week and will do it on 14-15 May .

Sorry for the delay caused

**Comment by internetmosquito** [comment]
@kapoorutd please use this icon for this

![00189c7eddbe8fa8b0eb6cb6d27d4ee0](https://user-images.githubusercontent.com/1500392/57335452-f41ed980-7122-11e9-8243-6c36dfad82c3.png)

**Comment by kapoorutd** [comment]
@internetmosquito 
We have made the following changes for above implementation..
1. Added a new button next to show details that will show a PDF with roster data for the selected lab (for now this code is commented).
2. Written the code for requester that will request the roster details Api.
3. Added a FileManager class which will help to mage file operation from "pdf data specified base64 encoded" and its implementation to show the roster details.


@alexey-ku77 
1. Fetching the data for pdf  "Via json body with pdf data specified base64 encoded " would be the more convenient way to retrieve the pdf. 
2. Please provide the roster Api collections which will be helpful to implement the pending task.

**Comment by internetmosquito** [comment]
@kapoorutd the new endpoint is /program/{id}/roster

![image](https://user-images.githubusercontent.com/1500392/57982159-e2ea9c80-7a41-11e9-802d-3dec0065120f.png)

**Comment by kapoorutd** [comment]
@internetmosquito 

We have implemented the above api but getting 404 error (NOT FOUND). 

Here is the request and respone..

Requested Url : http://test.wizbots.com/api/programs/5a0a0f1f0d12a96355f421f7/roster 

Response : {protocol=http/1.1, code=404, message=NOT FOUND, url=http://test.wizbots.com/api/programs/5a0a0f1f0d12a96355f421f7/roster}

Please provide the updated swagger link which will be helpful to implement Api's.

**Comment by kapoorutd** [comment]
@internetmosquito 
Can you please update us about the above API status, so that we can implement the pending task.

**Comment by internetmosquito** [comment]
@kapoorutd  please try now, it should be working in staging fine

**Comment by kapoorutd** [comment]
@internetmosquito 

Thanks for your contiguous support.

We have implemented the above API and its related pending task and tested the implemented changes,
it's working fine from our end.

We have check-In the code in **m_zero** branch.

Please have a look into the implemented task and confirm from your side.

**Comment by kapoorutd** [comment]
Hi @internetmosquito ,

Hope you are doing well...

Please update us about the above API implementation.
Once again we are getting **404 response code** from API.

Please do the needful changes and confirm from your end.
