### ISSUE TITLE
Not possible to go back to lab list in this situation

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#129]
In version 1.9.0 build is not possible to redirect to the Lab List from absences view
Way to reproduce:

- login in labtab
- tap in Lab List
- select a program
- tap absences
- select a member
- tap to add video at the absences view
- tap on lab list, nothing happens

And it's possible to redirect to any section, such as: Video List, etc., except the Lab List.

Attaching logs 
[LabtabLogs0 (1).txt](https://github.com/wizbots/labtab/files/3146111/LabtabLogs0.1.txt)

**Comment by kapoorutd** [comment]
@internetmosquito 
We have fixed this above issue and checked-in the code in **m_zero** branch.
