### ISSUE TITLE
Video uploading and syncing module

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#13]
We need a module that keeps on checking internet connectivity and syncs videos for current logged mentor with Wizbots

This is tigthly coupled with https://github.com/wizbots/labtab/issues/12, but I don't want to polute the view logic with this other logic we will need to communicate with server and keep videos synced...think of this as a controller in MVC terms

**Comment by kapoorutd** [comment]
Yes that wouldnt be an issue. Everything would be designed as per MVC while
considering SOLID principles.

**Comment by internetmosquito** [comment]
@kapoorutd what would be an issue? It is up to you to define how you structure this, but from my experience, I think we need to keep this separated :) This also probably applies to the lab data sync stuff, we might need another module to deal with that

**Comment by kapoorutd** [comment]
Yes it would be separated ..Both data and Controller layer.  There wont be
any issue keeping it through MVC.
