### ISSUE TITLE
Make some changes on LabTab Binder

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#130]
We need to do the following changes on LabTab Binder

1. Please remove "Contact List Summer 2018" from LabTab Binder and place the following docs inside a new folder called Contact Info:

[Contact Info - Summer 2019.pdf](https://github.com/wizbots/labtab/files/3265704/Contact.Info.-.Summer.2019.pdf)

[The Faces of Wizbots - 2019.pdf](https://github.com/wizbots/labtab/files/3265751/The.Faces.of.Wizbots.-.2019.pdf)

2.Create a folder called WizQuiz & Answers

Remove old PDF files

1. Lab Certified Quiz.pdf
2. Explorer Quiz.pdf
3. Apprentice QUIZ.pdf
4. Maker QUIZ.pdf
5. Imagineer QUIZ.pdf
6. Wizard QUIZ.pdf
7. Master Quiz.pdf
WizQuiz Answers.pdf

And inside the folder created above add the new ones

[7. Master Quiz.pdf](https://github.com/wizbots/labtab/files/3265769/7.Master.Quiz.pdf)
[6. Wizard QUIZ.pdf](https://github.com/wizbots/labtab/files/3265770/6.Wizard.QUIZ.pdf)
[1. Lab Certified Quiz.pdf](https://github.com/wizbots/labtab/files/3265772/1.Lab.Certified.Quiz.pdf)
[4. Maker QUIZ.pdf](https://github.com/wizbots/labtab/files/3265773/4.Maker.QUIZ.pdf)
[2. Explorer Quiz.pdf](https://github.com/wizbots/labtab/files/3265774/2.Explorer.Quiz.pdf)
[3. Apprentice QUIZ.pdf](https://github.com/wizbots/labtab/files/3265775/3.Apprentice.QUIZ.pdf)
[5. Imagineer QUIZ.pdf](https://github.com/wizbots/labtab/files/3265776/5.Imagineer.QUIZ.pdf)
[WizQuiz Answers.pdf](https://github.com/wizbots/labtab/files/3265753/WizQuiz.Answers.pdf)

3. Please install these docs into the LabTab Binder in the root directory and remove old ones (if any):

- Board Game Rules

[Board Game Rules.pdf](https://github.com/wizbots/labtab/files/3265754/Board.Game.Rules.pdf)

- Discipline In The Lab

[Discipline In The Lab.pdf](https://github.com/wizbots/labtab/files/3265755/Discipline.In.The.Lab.pdf)

- How To Train LIT

[How To Train LIT.pdf](https://github.com/wizbots/labtab/files/3265757/How.To.Train.LIT.pdf)

- In-Lab Photos

[In-Lab Photos.pdf](https://github.com/wizbots/labtab/files/3265758/In-Lab.Photos.pdf)

**Comment by kapoorutd** [comment]
@internetmosquito 
We are looking into it, will update you once it complete.

**Comment by kapoorutd** [comment]
@internetmosquito 
We have implemented the above requirements and replaced the old files with new files, also removed the remaining files (if any) as suggested.
Please have a check into the implemented changes and confirmed from your end.

**Comment by internetmosquito** [comment]
@kapoorutd thanks, checking

**Comment by kapoorutd** [comment]
@internetmosquito 
We have replace the icon for the roster button and checked-in the code in **m_zero** branch.

**Comment by internetmosquito** [comment]
@kapoorutd there's an issue with the Board Games Rules PDF, it's display wrong both in landscape and portrait modes, making it very hard to read

Landscape:

![view](https://user-images.githubusercontent.com/1500392/59554177-60e98700-8f9f-11e9-8ad1-f39b6fc661ac.png)

Portrait:

![view_portrait](https://user-images.githubusercontent.com/1500392/59554180-69da5880-8f9f-11e9-8574-501f2e4f99ed.png)

Please fix this

**Comment by kapoorutd** [comment]
@internetmosquito 
Hope you are doing well...

We are looking into it, we will update you once it get resolved.

**Comment by kapoorutd** [comment]
@internetmosquito 
The display mode issue was occurring because we have wrong display mode PDF file for Board Games Rules.
We have change the display mode of  Board Games Rules PDF file and replaced with current PDF file, Now its working fine.
Added  Implementation :

As this file is taking some time to render the data on screen, so we have added a progress bar on this screen, So that the user get to know that the file is currently loading.

Please, get a chance to look into the implemented changes and confirm from your end.

**Comment by internetmosquito** [comment]
@kapoorutd awesome, testing

**Comment by internetmosquito** [comment]
all fixed, closing
