### ISSUE TITLE
Mockup the Home and Login screens

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#2]
Mockup the login screen and Home page for the app.

Login page can be very similar to what we have in Wizbots now, need to confirm with Sourabh if we're going to use HTML or typical Android layouts for the views though

Home page we have to decide how we build it, we should have quick access to the main important things:

* Video list
* Lab list
* Lab view
* Record video
* Access to profile view

**Comment by solnishka** [comment]
@internetmosquito , as for login page I think the best way is to leave what we have for our site - it's easy and wizbots style fit. Just make modals as pages:

![login](https://cloud.githubusercontent.com/assets/9883696/20000988/243e085c-a28b-11e6-8fe6-67c32a09a867.jpg)

![password-reminder](https://cloud.githubusercontent.com/assets/9883696/20000995/2fd15476-a28b-11e6-9d5a-ee7865b63096.jpg)

![create-an-account](https://cloud.githubusercontent.com/assets/9883696/20001004/3dc38b30-a28b-11e6-8a8b-35758d033c11.jpg)

This style is familiar to all Wizbots family members and will be easy to use for everybody

**Comment by internetmosquito** [comment]
@solnishka agreed, but I don't think we need the create account one... I don't expect new mentors to signup using Labtab...at least not for now, we can skip it

**Comment by solnishka** [comment]
@internetmosquito , no problem:)

**Comment by solnishka** [comment]
About the home page, I see it like that:

I'm not sure yet what we'll have in the header and footer but I think that we'll understand all the informations while developing, for now the main is general style. Also I think that for mobile it's much better to have just main buttons that will follow members to the functionality they need. Now we have space for 2 more buttons, for now they can follow, e.g. to the web and smth else, or just leave it like it is but in the future if the functionality becomes wider we'll just add new button without any problems. 
@internetmosquito, what do you think?

**Comment by solnishka** [comment]
About the home page, I see it like that:

I'm not sure yet what we'll have in the header and footer but I think that we'll understand all the informations while developing, for now the main is general style. Also I think that for mobile it's much better to have just main buttons that will follow members to the functionality they need. Now we have space for 2 more buttons, for now they can follow, e.g. to the web and smth else, or just leave it like it is but in the future if the functionality becomes wider we'll just add new button without any problems. 
@internetmosquito, what do you think?

**Comment by solnishka** [comment]
![home-page](https://cloud.githubusercontent.com/assets/9883696/20003543/1deb99f8-a298-11e6-8b70-cf830856e328.jpg)

**Comment by internetmosquito** [comment]
Ok, let's add Sourabh into this, but if you recall the document, the only thing mentors can access would be: video list, lab list, lab view, and probably another button to record video from this main screen

I like the idea of having a button to go to Wizbots.com, that would mean opening the tablet browser.

**Comment by solnishka** [comment]
@internetmosquito , sure - there can be added any buttons we need, just decided to use the desktop design we already have cause as I have already told - it's much better to use the same style in the connected apps - it's much more user-friendly for the mentors.

**Comment by internetmosquito** [comment]
@solnishka Ok, I like it but we need to change buttons to be 

    Go to Wizbots -> Opens web browser
    Video list
    Lab list
    Lab view
    Record video
    Access to profile view -> Not really sure about this one yet, not sure if we need the mentor to change his profile from here

What you think about this one @kapoorutd ? Doable?

**Comment by solnishka** [comment]
What do you think about this one?
![home-page-2](https://cloud.githubusercontent.com/assets/9883696/20141435/66a8b704-a6a1-11e6-92a2-8ee62bc4293b.jpg)
