### ISSUE TITLE
We need to show sync status all across the app

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#20]
Right now we're only showing sync status in the videos list screen

We need to extend this all over the application. Keeping in mind this is an off-line first application where connectivity must be treated as a bonus (not for granted), mentors must be always be aware of the sync status in several places:

* Mentor profile 
* Students
* Student profile
* Lab list
* Lab details
* Video list
* Video details

@solnishka , please think of what kind of icon we can use to highlight current view mentor is using is synced

@kapoorutd Please keep in mind this offline first approach at all times, app MUST BE usable at all times without internet connectivity, be able to detect when there is broadband connectivity and automatically sync ....is this clear? Do you need anything specific for this from back-end?

**Comment by solnishka** [comment]
I suggest the following:

synced:
![synced](https://cloud.githubusercontent.com/assets/9883696/21136441/b79aa33e-c136-11e6-887b-dd92f9e701d5.png)

not synced:
![notsynced](https://cloud.githubusercontent.com/assets/9883696/21136448/be9fd9ba-c136-11e6-8cc9-39b424501101.png)

**Comment by internetmosquito** [comment]
@solnishka ok, where and on which views will this be shown?

**Comment by solnishka** [comment]
I think it's good to see the connection on every page.
done, please take a look: https://projects.invisionapp.com/d/main#/projects/prototypes/9523180

**Comment by internetmosquito** [comment]
@solnishka looks good to me, @kapoorutd any toughts on this? Can we show this on every screen? It would be great if we can show sync status per view, otherwise we will show "not synced" if anything seems not synced
