### ISSUE TITLE
Add missing data in lab list view

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#21]
Current lab list is missing several things.

We need to be able to search or filter by:

* Location (this should be smart enough to use city or region, i.e., San Carlos, California)
* Dates: From-To is a must here
* Today-Tomorrow buttons, this is what really interests mentors (What do I have today or tomorrow?)

I'll add this location (since dates is already in the API)

@solnishka Please let me know if this is clear, I add this to the top before the list
@kapoorutd Is this feasible, let's see what Tanya comes up with and how we can integrate this in what's already done

**Comment by solnishka** [comment]
done, please take a look: https://projects.invisionapp.com/d/main#/projects/prototypes/9523180

**Comment by internetmosquito** [comment]
@solnishka looking good, @kapoorutd please update the view accordingly (screen 6 in InVisio)
