### ISSUE TITLE
Change the lab details view to include more data

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#22]
Current lab details view is missing some key information

* SKU
* Availability
* Category
* Name
* Location
* Season
* Room
* Grades
* Capacity
* Sessions
* From-To dates
* List of skips (Student-Date-Reason)

Besides for each student enroll, we need to specify:

* Self-checkout
* Pickup instructions
* In-out times
* Notes

Pretty much as the PDF attached, but we should show this info in lab details view per student

[25356.pdf.zip](https://github.com/wizbots/labtab/files/648209/25356.pdf.zip)

@solnishka I understand this will require some iterations until we nail it, let's discuss this via voice if you want, I can show you how this info is presented nowadays in Wizbots to mentors

@kapoorutd I'm gonna add this info to the API so you get all this wihtout problems

**Comment by solnishka** [comment]
done, could you please take a look - new slides 14 and 15

**Comment by internetmosquito** [comment]
@solnishka I've added comments to both, let me know if they're clear
