### ISSUE TITLE
Remove Actions word in last column of lab views

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#23]
Seems misleading please remove "Actions" from Lab list and Lab details table, not the column, just the work "Actions"

**Comment by solnishka** [comment]
done, please take a look: https://projects.invisionapp.com/d/main#/projects/prototypes/9523180

**Comment by internetmosquito** [comment]
@solnishka looking good, thanks, @kapoorutd please update views accordingly

**Comment by internetmosquito** [comment]
done
