### ISSUE TITLE
Misleading message when selecting a lab with no connectivity not previously visited

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#35]
We have a misleading message when selecting a lab in offline mode we haven't visited with connectivity (aka no local data in local db).

It says "No Internet connection", when it should be "No data available, please try again later with Internet connectivity"

How to reproduce:

1.- Go to Lab list
2.- Make a search
3.- Go offline
4.- Make sure you select a not previously visited Lab
5.- You will see a toast saying No Internet connection

**Comment by kapoorutd** [comment]
When a user is offline and haven't visited lablist with connectivity then this will show "No data available, please try again later with Internet connectivity" but a user is connected to internet and click to view lablist and response data is zero then this will show "No Lab Found"

**Comment by internetmosquito** [comment]
@kapoorutd ok
