### ISSUE TITLE
Add legend on top of student list

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#50]
We need to add a legend on top of student's list to explain what each icon means, check image below

![legend](https://user-images.githubusercontent.com/1500392/27057500-c97960d4-4fcc-11e7-85d7-f4fc9786dbdb.png)

Let me know if this is doable both in portrait and landscape mode

**Comment by kapoorutd** [comment]
@internetmosquito 
On Landscape its possible. but on portrait view its not possible as per current UI.

**Comment by internetmosquito** [comment]
@kapoorutd Ok, can you change to just text in portrait mode instead of icons?

**Comment by internetmosquito** [comment]
@kapoorutd This is not ready, check the image:

![selection_130](https://user-images.githubusercontent.com/1500392/27245772-d1bb7966-52ed-11e7-9607-db670a800ce0.png)

We're missing the explanation for Projects, Wizchips and LabTime
Besides, is it possible in portrait mode to replace icons for text instead?

**Comment by internetmosquito** [comment]
@kapoorutd please make font smaller and align them properly in portrait mode to avoid this:

![rowview](https://user-images.githubusercontent.com/1500392/28206917-15f2a7e4-6888-11e7-8e70-b7f1d2f48497.png)

**Comment by internetmosquito** [comment]
@kapoorutd this is not fixed yet, if you have to make font smaller so they're properly aligned, do so

![selection_194](https://user-images.githubusercontent.com/1500392/28727235-6c0fcc1e-73c4-11e7-9b46-1b898f64538c.png)

**Comment by internetmosquito** [comment]
@kapoorutd This is not fixed yet, I understand is hard, but it I see no improvements at all, check image below, tested on real device on portrait mode, looks exactly the same as my previous comment

![screenshot_20170815-121338](https://user-images.githubusercontent.com/1500392/29311922-a6e5f96a-81b3-11e7-97b4-4619967d1570.png)

**Comment by internetmosquito** [comment]
Guess this will never work as expected, I'll leave it out for new redesign later
