### ISSUE TITLE
Statistics not diplaying correctly in many programs

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#55]
Steps to reproduce:
* Login with judy@wizbots.com
* Select Lab List
* Click to find Oak Knoll Elementary from location
* Click to view a program
* Click edit the member to view a statistics

Check the image below

![statistics](https://user-images.githubusercontent.com/1500392/27058329-cf047d96-4fd0-11e7-8ca2-1acae65021f9.png)

**Comment by kapoorutd** [comment]
@internetmosquito 
Statistics data displays on the basis of  API response. 
API 
http://test.wizbots.com/api/students/4ffe3f4e41af8c5199000038
Response 
{
    "enrollments_count": "4",
    "last_name": "Yates",
    "date_of_birth": "2006-07-19 00:00:00",
    "creator": {
        "phone_2": "",
        "email": "sarah@laneyates.com",
        "phone_1": "6508236868"
    },
    "grade": "2",
    "wizchips": 0,
    "after_care_after": "No",
    "id": "4ffe3f4e41af8c5199000038",
    "first_name": "AnnaJulia",
    "level": "Apprentice",
    "absence_count": "1",
    "allergies": "none",
    "special_needs": "",
    "after_care_before": "No",
    "projects_history": {
        "imagineer": {
            "lab_time": 0,
            "imagineering": [],
            "mechanisms": [],
            "programming": [],
            "structures": [],
            "projects": [
                {
                    "projectStatus": "",
                    "projectName": "counting"
                },
                {
                    "projectStatus": "",
                    "projectName": "boolean logic"
                },
                {
                    "projectStatus": "",
                    "projectName": "rotation sensor"
                },
                {
                    "projectStatus": "",
                    "projectName": "etch-a-sketch"
                },
                {
                    "projectStatus": "",
                    "projectName": "compass sensor"
                },
                {
                    "projectStatus": "",
                    "projectName": "north pole express"
                },
                {
                    "projectStatus": "",
                    "projectName": "slider crank"
                },
                {
                    "projectStatus": "",
                    "projectName": "magnetic sensor"
                },
                {
                    "projectStatus": "",
                    "projectName": "shell game"
                },
                {
                    "projectStatus": "",
                    "projectName": "ackerman"
                },
                {
                    "projectStatus": "",
                    "projectName": "steering"
                }
            ]
        },
        "explorer": {
            "lab_time": 0,
            "imagineering": [
                "Brainstorming",
                "Planning"
            ],
            "mechanisms": [
                "Differential Drive Vehicle"
            ],
            "programming": [
                "Display Control",
                "Flow Control - 1",
                "Speaker Control",
                "Tool Chain - 2"
            ],
            "structures": [
                "PVC Pipe Structure",
                "Rigid Beam",
                "Wizbits",
                "Wizbrick",
                "Zoob Blocks"
            ],
            "projects": [
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "windscreen wiper"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "bumper car"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "hello world!"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "sound and music"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "plastic fabtastic"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "tallest robot"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "led wand"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "dancing puppets"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "parallerl programming"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "diff drive control"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "wizball"
                }
            ]
        },
        "wizard": {
            "lab_time": 0,
            "imagineering": [],
            "mechanisms": [],
            "programming": [],
            "structures": [],
            "projects": [
                {
                    "projectStatus": "",
                    "projectName": "algorithms"
                },
                {
                    "projectStatus": "",
                    "projectName": "gyroscope"
                },
                {
                    "projectStatus": "",
                    "projectName": "data structures"
                },
                {
                    "projectStatus": "",
                    "projectName": "accelerometer"
                },
                {
                    "projectStatus": "",
                    "projectName": "camera"
                }
            ]
        },
        "master": {
            "lab_time": 0,
            "imagineering": [],
            "mechanisms": [],
            "programming": [],
            "structures": [],
            "projects": [
                {
                    "projectStatus": "",
                    "projectName": "objects"
                },
                {
                    "projectStatus": "",
                    "projectName": "networking"
                },
                {
                    "projectStatus": "",
                    "projectName": "behaviors"
                },
                {
                    "projectStatus": "",
                    "projectName": "pid control"
                },
                {
                    "projectStatus": "",
                    "projectName": "segway"
                }
            ]
        },
        "lab certified": {
            "lab_time": 0,
            "imagineering": [],
            "mechanisms": [],
            "programming": [
                "Motor Control",
                "NXT Button Control",
                "Tool Chain - 1",
                "Touch Sensor Control"
            ],
            "structures": [],
            "projects": [
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "tick tock"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "hypnotizer"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "chariot"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "obstacle course"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "build strong"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "castles and catapults"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "the wizbots way"
                },
                {
                    "projectStatus": "SKIPPED",
                    "projectName": "madlib"
                }
            ]
        },
        "maker": {
            "lab_time": 0,
            "imagineering": [],
            "mechanisms": [],
            "programming": [
                "Line Following",
                "Parallel Programming"
            ],
            "structures": [],
            "projects": [
                {
                    "projectStatus": "",
                    "projectName": "line following"
                },
                {
                    "projectStatus": "",
                    "projectName": "line racing"
                },
                {
                    "projectStatus": "",
                    "projectName": "using the force"
                },
                {
                    "projectStatus": "",
                    "projectName": "drag racing"
                },
                {
                    "projectStatus": "",
                    "projectName": "hoist"
                },
                {
                    "projectStatus": "",
                    "projectName": "elevator"
                },
                {
                    "projectStatus": "",
                    "projectName": "screw gear"
                },
                {
                    "projectStatus": "",
                    "projectName": "slow poke"
                }
            ]
        },
        "apprentice": {
            "lab_time": 0,
            "imagineering": [
                "Troubleshooting"
            ],
            "mechanisms": [],
            "programming": [
                "Color Sensor Control",
                "Distance Sensor Control",
                "LED Wand",
                "Light Sensor Control",
                "Line Following",
                "Parallel Programming",
                "Sound Sensor Control"
            ],
            "structures": [
                "A-Frame",
                "Cube"
            ],
            "projects": [
                {
                    "projectStatus": "PENDING",
                    "projectName": "troubleshooting"
                },
                {
                    "projectStatus": "PENDING",
                    "projectName": "wheel free racing"
                },
                {
                    "projectStatus": "PENDING",
                    "projectName": "distance sensor"
                },
                {
                    "projectStatus": "PENDING",
                    "projectName": "table top survival"
                },
                {
                    "projectStatus": "PENDING",
                    "projectName": "sound sensor"
                },
                {
                    "projectStatus": "PENDING",
                    "projectName": "barking dog"
                },
                {
                    "projectStatus": "PENDING",
                    "projectName": "light sensor"
                },
                {
                    "projectStatus": "PENDING",
                    "projectName": "sun flower"
                },
                {
                    "projectStatus": "PENDING",
                    "projectName": "color sensor"
                },
                {
                    "projectStatus": "PENDING",
                    "projectName": "red light green light"
                },
                {
                    "projectStatus": "PENDING",
                    "projectName": "random numbers"
                },
                {
                    "projectStatus": "PENDING",
                    "projectName": "floor sweeper"
                }
            ]
        }
    },
    "after_care_phone": null,
    "after_care_name": null
}

**Comment by internetmosquito** [comment]
@kapoorutd this is not related with the values of statistics but with how they're displayed

This is the original transcript from Dima:

> 
> The statistics section is displayed incorrectly, but it's appears not for all the programs. And incorrect view appears just for the vertical position of the Tab. The statistics appears as a small section:
> 
>   Actions to reproduce:
>        login at the labtab with judy@wizbots.com
>        select Lab List
>        click to find Oak Knoll Elementary from location
>        click to view a program
>        click edit the member to view a statistics
>   Actual:
>         please review: http://www.screencast.com/t/hxmeHwFdTH
>         However it's possible to scroll it.
>         It's actually not just for this program, looks like there are many programs with
> incorrect view, but not all of it. There are programs with correct statistics view.

**Comment by internetmosquito** [comment]
@kapoorutd I think what Dima meant is that there is no knowledge nuggets in that case....I've replicated steps, found this:

![selection_125](https://user-images.githubusercontent.com/1500392/27171276-4ea64d36-51b1-11e7-89b7-3d1805f4391f.png)

Even if the kid has no nuggets from API response, we should show the columns too, but to be honest I couldn't find any kid in any program where I could see the nuggets...

**Comment by internetmosquito** [comment]
@kapoorutd Ok, found what the issue is

1.- Go to Lab List
2.- Select Oak Elementary School
3.- Click Pencil button for first kid in landscape mode
4.- Switch to portrait
5.- Scroll down to statistics

Depending on "whatever reason", the number of rows shown in statistics section varies, from 1 to 2, 3, 4, etc. If you switch to Landscape, on the other hand, all rows are shown. Why we need to scroll the statistics section in portrait but not in landscape? Just scroll the "whole page", but not the statistics table. Show all rows by default.
