### ISSUE TITLE
Wizchips 

### ISSUE THREAD

**Issue by JoshuaWizbots** [wizbots/labtab#79]
I gave kids wizchips today on the labtab and when the page was exited and I returned there were a larger number of wizchips added automatically.

Example: I gave John 7 wizchips and when I returned to same page later he had 76, then after returning later he had 661. This all happened in minutes during one lab.

Please stabilize wizchip count to remain the same until added or subtracted by instructor.

**Comment by internetmosquito** [comment]
Duplicate, working on this already
