### ISSUE TITLE
Editing access to student profiles

### ISSUE THREAD

**Issue by JoshuaWizbots** [wizbots/labtab#85]
Please allow instructor to select student (check box) click on edit button (picture of pencil) and have access to make changes with details on student profile. We would like access to change all details in profile and to be able to change numbers for all data collected for knowledge nuggets to correct or make current.

**Comment by internetmosquito** [comment]
@kapoorutd have a look at this please

**Comment by internetmosquito** [comment]
Duplicate, closing
