### ISSUE TITLE
Make Wizchips field editable

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#86]
We need to be able to reset Wizchips for selected student

![screenshot_20180517-235904](https://user-images.githubusercontent.com/1500392/40206013-9a8864f6-5a2e-11e8-9ca0-da21db540e95.png)

Make field editable, you'll have to use a new API endpoint for this

**Comment by kapoorutd** [comment]
@internetmosquito please share the api endpoint for profile update.

**Comment by kapoorutd** [comment]
@internetmosquito Can you please share the API endpoint so that we can directly update the wizchips otherwise we can show a button that increments/decrements and use existing api..
