### ISSUE TITLE
Wizchips balance totally wrong for some labs 

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#87]
We originally thought this was related with https://github.com/wizbots/wizbots/issues/2304 but we doubt it since it seems for some reason labtab called the endpoint with incredibly high values

We will enforce the API endpoint so it only allows increasing or decreasing by one, but obviously there's something wrong here.

Here's a video showing this behaviour

[20180516_160424.mp4.zip](https://github.com/wizbots/labtab/files/2014866/20180516_160424.mp4.zip)

Please check what's going on here.

**Comment by kapoorutd** [comment]
@internetmosquito Please provide the steps to reproduce the issue.

**Comment by alexey-ku77** [comment]
@kapoorutd hello!
Currently there is no way to reproduce the issue.
I'm aware of two incidents at the moment.
Both times mentor - Joshua Musial.
1-st. 34697. Tue Apr 17 00:54:04 2018 GMT (Mon Apr 16 17:54:04 2018 PST)
2-nd. 35561. Wed May 16 22:35:23 2018 GMT (Wed May 16 15:35:23 2018 PST)

Here is all requests except wizchips=1.
[wizchips_logs.txt](https://github.com/wizbots/labtab/files/2025997/wizchips_logs.txt)
Here is all requests with those.
[wizchips_full_logs.txt](https://github.com/wizbots/labtab/files/2026001/wizchips_full_logs.txt)

**Comment by kapoorutd** [comment]
@internetmosquito Hi, I am unable to figure-out the problem, please provide more information about the issue. when we tested wizchips count, it was increasing and decreasing by one every time.

**Comment by internetmosquito** [comment]
@kapoorutd Not sure what more info I can provide...you have a video showing the issue, log traces that show labtab made a requests with very high values, not just 1....what else do you need? 

On the backend will we modify endpoint so it only allows +-1 increments / decrements, but it is obvious that something's wrong on labtab side, do we agree on that?

Do you have any logs of what you do in labtab? We will definetely need to start thinking on storing those somewhere...we're going blind here otherwise
