### ISSUE TITLE
Provide labtab logs to some place so we can examine them if needed

### ISSUE THREAD

**Issue by internetmosquito** [wizbots/labtab#89]
Based on the video issue, we need more logging in terms of labtab. 

Please send logs to wizbots or let us know how we can access them somewhere in case we need to debug.

**Comment by kapoorutd** [comment]
Adding log utility so that its possible.

**Comment by internetmosquito** [comment]
@kapoorutd is this ready?

**Comment by kapoorutd** [comment]
@internetmosquito Hello, there are two places in the application from where you can send the Log report as an attachment as mentioned below -
1. From the Login window - 
    Long press the "LabTab" icon which is at the top left corner of the window.
    The "send logs" pop up will appear. 
    select Email/Gmail option to send it through email.
    once you will select email option the log file will be attached on the email and you can send it further.

2. If you are already logged in - 
    Go to navigation drawer.
    Long press on "Student" icon which is at the top of the drawer.
    The "send logs" pop up will appear. 
    select Email/Gmail option to send it through email.
    once you will select email option the log file will be attached on the email and you can send it further.

Please note - I have mentioned the log statement at every requester.

**Comment by internetmosquito** [comment]
Seems to work
